- name: Gimme some pip
  apt: name=python-pip state=latest

- name: Install/upgrade gomatic for GoCD wrangling
  pip: name="gomatic" state=latest

- name: install build-essential
  apt: name=build-essential state=present

- name: install libpq-dev
  apt: name=libpq-dev state=present

- name: install libmysqlclient-dev
  apt: name=libmysqlclient-dev state=present

- name: I need parallel
  apt: name=parallel state=latest

- name: install libsqllite3-dev
  apt: name=libsqlite3-dev state=present

- name: ab for perf testing
  apt: name=apache2-utils

- name: setup go .bashrc
  copy: src=.bashrc dest=/var/go/.bashrc owner=go group=go mode=0644

- name: setup java 8 as default java
  file: src=/usr/lib/jvm/java-8-oracle dest=/usr/lib/jvm/default-java state=link

- name: create our pipelines
  script: ./configure_gocd.py
  environment:
    CF_USERNAME: CF_USERNAME
    CF_PASSWORD: CF_PASSWORD
